language: python
 
python:
  - "3.4"

install:
  - pip install -r requirements-dev.txt

jobs:
  include:
    -stage: test
    script:
      - pylint -d R -d C -e missing-docstring sources
 
    -stage: docs
    script:
      - python -munittest discover -s tests
